////////////////////////////////////////////////////////////////////////////////
//
//    Copyright (c) 2022 - 2024.
//    Haixing Hu, Qubit Co. Ltd.
//
//    All rights reserved.
//
////////////////////////////////////////////////////////////////////////////////
package ltd.qubit.commons.datastructure;

import java.util.Collection;
import java.util.Iterator;
import java.util.NoSuchElementException;
import java.util.function.Function;
import java.util.function.Supplier;

/**
 * A lazy iterable.
 * <p>
 * This class provides a way to create an iterable which generates its elements
 * lazily. The elements are generated by a supplier. The supplier will be called
 * every time when the iterator requests the next element.
 *
 * @param <T>
 *      the type of the elements of this iterable.
 */
public class LazyIterable<T> implements Iterable<T> {
  private final Supplier<T> supplier;
  private final int size;

  /**
   * Constructs a new lazy iterable.
   *
   * @param size
   *     the number of elements to be iterated.
   * @param supplier
   *     the supplier which generates the elements of the iterable.
   */
  public LazyIterable(final int size, final Supplier<T> supplier) {
    this.size = size;
    this.supplier = supplier;
  }

  /**
   * Constructs a new lazy iterable.
   *
   * @param <E>
   *     the type of the source elements.
   * @param col
   *     a collection of source elements which will be mapped to the elements to
   *     be iterated.
   * @param mapper
   *     the mapper functor which maps the source elements to the elements to be
   *     iterated.
   */
  public <E> LazyIterable(final Collection<E> col, final Function<E, T> mapper) {
    this.size = col.size();
    final Iterator<E> iter = col.iterator();
    this.supplier = () -> mapper.apply(iter.next());
  }

  /**
   * Constructs a new lazy iterable.
   *
   * @param <E>
   *     the type of the source elements.
   * @param array
   *     a array of source elements which will be mapped to the elements to
   *     be iterated.
   * @param mapper
   *     the mapper functor which maps the source elements to the elements to be
   *     iterated.
   */
  public <E> LazyIterable(final E[] array, final Function<E, T> mapper) {
    this.size = array.length;
    final Iterator<E> iter = new ArrayIterator<>(array);
    this.supplier = () -> mapper.apply(iter.next());
  }

  @Override
  public Iterator<T> iterator() {
    return new LazyIterator();
  }

  private class LazyIterator implements Iterator<T> {
    private int index = 0;

    @Override
    public boolean hasNext() {
      return index < size;
    }

    @Override
    public T next() {
      if (index >= size) {
        throw new NoSuchElementException();
      }
      ++index;
      return supplier.get();
    }
  }
}
